name: darwin
version: 0.5.0
description: >
  A genetic/evolutionary algorithm library for Dart. Given a population
  of phenotypes, an evaluator (fitness function), and time, the algorithm
  will evolve the population until it crosses given fitness threshold.
homepage: https://github.com/filiph/darwin

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.1.6

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.0.0
